#!/bin/bash

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
        oIFS=$IFS
        IFS='
        '
        SFILES="$1"
        IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo -e "\033[0;32m"Validating PHP Lint..."\033[0m"
for FILE in $SFILES
do
        php -l -d display_errors=0 $PROJECT/$FILE
        if [ $? != 0 ]
        then
                echo -e "\033[41m"Fix the error before commit."\033[0m"
                exit 1
        fi
        FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then

    echo -e "\033[0;32m"Validating Magento2 Coding Standard."\033[0m"
        ./vendor/bin/phpcs --standard=Magento2 $FILES

        if [ $? != 0 ]
        then
                echo -e "\033[41m"Fix the error before commit."\033[0m"
                exit 1
        fi

    echo -e "\033[0;32m"Validating Completed"\033[0m"

fi

exit $?
